### ISSUE TITLE
关于set的扩展

### ISSUE THREAD

**Issue by sunnyzhouy** [aralejs/base#10]
举例：

``` javascript
    ......
  attrs = {
    item:{
      name:'xxx',
      products:[1,2,3]
    }
  }
  ......

this.set('item',{});

this.get('item'); // -> item:{ name:'xxx', products:[1,2,3]}
```

也就是说set方法会自动merge，并在没有已经存在的属性值的情况下，使用原属性值。

我现在遇到的情况需要在没有值的情况下，强制覆盖掉原属性值，也就是得到结果：item:{}。

可以提供扩展么？

**Comment by lepture** [comment]
可以设计成

```
set('item', {}, false)
```

**Comment by lianqin7** [comment]
@lepture 现在set已经有第三个参数`option`了，不过目前只有一个选择

``` js
// option.silent: true 表示不触发对应的 'change' 事件，默认为false
set(attr, val, options);
```

可以考虑增加

``` js
// option.override: true 表示不做merge，直接覆盖，默认为false
```

**Comment by popomore** [comment]
恩，这个可以考虑

**Comment by lianqin7** [comment]
@popomore @leoner 

不小心改了主干，等我回滚下：（

**Comment by lifesinger** [comment]
这个建议，下周讨论下，可以考虑

On Fri, Mar 29, 2013 at 2:05 PM, Haoliang Gao notifications@github.comwrote:

> 恩，这个可以考虑
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aralejs/base/issues/10#issuecomment-15629968
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by popomore** [comment]
这个已经修改
