### ISSUE TITLE
谈谈 parseEventsFromAttrs

### ISSUE THREAD

**Issue by popomore** [aralejs/base#15]
可能很多人都不知道这个功能，我也是最近看代码才发现的

```
var Test = Base.extend({
  attrs: {
    onFocus: spy1,
    onChangeXx: spy2,
    beforeShow: spy3
  },
  show: function() {}
});
```

看看这个功能是如何用的，可以将一个属性注册为事件，如

`onFocus` 会将函数注册到 'focus' 事件上，`onChangeXx` 会将函数注册到 'change:xx' 事件上。`beforeShow` 则是将函数注册到 'before:show' 事件上。

先从分类上说，before/after 是对方法做切面，change 监听属性的变化，on 是最普通的监听。这些都放到 attr 上会很混乱，容易造成误解。

从用户角度说，这些都可以用实例方法去实现，更加优雅，如

```
var t = new Test();
t.on('focus', function() {}); 
t.before('show', function() {}); 
t.on('change:xx', function() {}); 
```

所以我觉得这个功能可以去掉。

**Comment by lifesinger** [comment]
赞同，这个可以去掉

**Comment by lianqin7** [comment]
。。。。。这个去掉了。。。晕死，又要自己写一堆hack了

**Comment by lianqin7** [comment]
`beforeShow,afterHide,onClose`这些用法在api设计里面很常见啊，从api设计及使用者方便的角度来说，是 **方便且合理的**

何必要纠结是否会造成attr的混乱呢？毕竟 **很多使用者并没有 `config === attr` 的意识，也不会去在乎内部的实现，只要好用就行**，`config === attr`也是很不合理的

**Comment by lianqin7** [comment]
@popomore @lifesinger 

请考虑下实际的使用者场景，比如现在的 

https://github.com/aralejs/dialog   @afc163 

https://github.com/aralejs/validator @shaoshuai0102

**Comment by lianqin7** [comment]
@popomore  onChange确实用得比较少，after/before + on 还是很常见的说。。。

**Comment by afc163** [comment]
dialog 里的确有 onConfirm 和 afterHide 的使用方法。

对于有实例的调用可以用下列方法替代：

``` js
instance.on('confirm', function() {});
```

这是没有问题的，但是在 confirmbox 里有这样的静态调用。

``` js
Confirmbox.confirm('内容', '标题' , function() {}, {
    onConfirm: function() {},
    beforeHide: function() {}
});
```

这个正是利用 `parseEventsFromAttrs` 来完成的，如果去掉了，这种没有显式实例的调用方式，则不知道如何实现。

http://aralejs.org/dialog/examples/confirmbox.html

**Comment by popomore** [comment]
@lianqin7 是只保留一种使用方式，而不是不支持，用 attribute 和 events 的就好了。

**Comment by popomore** [comment]
@afc163 单例的参数也可以转化给实例的

```
ConfirmBox.show = function(message, callback, options) {

  new ConfirmBox()
    .on('confirm', options.onConfirm || function() {})
    .before('hide', options.beforeHide || function() {})
}
```

**Comment by lianqin7** [comment]
@popomore 但是把初始化的方式去掉了，在使用场景上就变得麻烦很多

比如

``` js

// 原来
new Xxx({
    onClose: funtion(){},
    afterShow: function(){}
});

// 现在
new Xxx({}).on('close', function(){}).after('show', function(){});

// 现在如果我想第一种用法保留，就必须去在Xxx的原型里显式指定了 :(
setUp: function(){
    if(this.get('onClose')){
        this.on('close', this.get('onClose'));
    }

    if(this.get('afterShow')){
        this.after('show', this.get('afterShow'));
    }
}
```

我想使用者大部分觉得第一种简单易记吧，特别是某些组合场景，只有 `原型+配置` 的情况，就一定要在原型里hack了，很不方便

**Comment by afc163** [comment]
@lianqin7 

使用方式上的一般是习惯，其实第一种情况也不简单，反而给使用者一个不知道和第二种方式有和区别的感觉。

统一的事件调用方式在实现上和代码风格上都很舒服。

**Comment by popomore** [comment]
我觉得这些本身就是事件，应该统一使用方式，不然会混淆。

有些组件是  `afterShow`，有些是 `after('show')`，还有可能 `on('after:show')`，对于刚开始使用的人来说很容易搞不清楚。

你觉得这个好用也许是先入为主，或者以前就是这么用的（确实以前的 Arale 也有这种 API）。

这个 API 本身也是内部使用的，并没有文档说明，在没有广泛使用之前把他干掉。

**Comment by lianqin7** [comment]
@afc163 @popomore

反正我是做好了把我们的组件全部hack一遍的准备了，这种api已经是团队的习惯了

**Comment by popomore** [comment]
使用方式上还是希望往事件上面靠

```
var t = new Test();
t.on('focus', function() {}); 
t.before('show', function() {}); 
t.on('change:xx', function() {});
```

**Comment by lianqin7** [comment]
我已经看到了各种枚举到死的感觉了：（

@afc163 你在`ConfirmBox`里要枚举多少事件？

还有 `popup` 是否要增加对 after/beforeShow 和  after/beforeHide 的api？

**Comment by lianqin7** [comment]
@popomore 

简单搜索了下，已经用到该特性并对外服务的代码大概有几十处了：（
这次修改对整站影响巨大啊

大部分是 popup 组件及衍生组件，所以对 popup 组件的支持是一定要保留的

**Comment by afc163** [comment]
基本上只需要针对三个方法 `onConfirm` 和 `beforeHide` 和 `afterHide`。

**Comment by lianqin7** [comment]
@afc163 我这边主要是  after/before + show/hide

**Comment by popomore** [comment]
@lianqin7 对外服务只是你们站内的组件？

**Comment by lianqin7** [comment]
@popomore 线上正式使用的，底层用的是arale的widget组件库

**Comment by lifesinger** [comment]
我说一下来由，支持 afterXxx / beforeXxxx，是参考了 MooTools 的设计。

给用户带来了一些简洁，但同时也造成了一些困扰，和 @popomore 讨论过，感觉能减则减，因此有这个调整。

On Wed, May 8, 2013 at 11:35 AM, lianqin7 notifications@github.com wrote:

> @afc163 https://github.com/afc163 我这边主要是 after/before + show/hide
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aralejs/base/issues/15#issuecomment-17584829
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by afc163** [comment]
这个改动不会影响到线上已有的调用的。后续升级 base & widget 后的基础上再使用，则需要注意。

**Comment by lianqin7** [comment]
@lifesinger 前段时间arale的培训里我还特意强调了这个方便的特性- -现在得群发邮件阻止大家使用这个接口了，蛋各种疼啊

**Comment by lifesinger** [comment]
@lianqin7 这个真心抱歉，我也想保留，但找不到合适的理由-.-

2013/5/8 lianqin7 notifications@github.com

> @lifesinger https://github.com/lifesinger 前段时间arale的培训里我还特意强调了这个方便的特性-
> -现在得群发邮件阻止大家使用这个接口了，蛋各种疼啊
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aralejs/base/issues/15#issuecomment-17585015
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by lianqin7** [comment]
@popomore @lifesinger 

突然想到一个问题，假设有这种情况

``` js
initialize: function(){
    this.trigger('init');
}
```

我该 **如何注册init事件**  呢？

是否能改造一下，不用 onXxx 的形式，改成如下方式注册，既能清晰表示事件，也没有那么多的潜规则

``` js
new Xxx({
    on: {
        'confirm': function(){},
        'close': function(){},
        'init': function(){}
    },
    before: {
        'show': function(){}
    },
    after: {
        'hide': function(){}
    }
});

// 或者
new Xxx({
    listeners: {
        on: {
            'confirm': function(){},
            'close': function(){},
            'init': function(){}
        },
        before: {
            'show': function(){}
        },
        after: {
            'hide': function(){}
        }
    }
});
```

**在 config 里指定事件注册，这个需求还是很强烈的** ，特别是某些 init 事件， **只有这种方法才能注册到** ，否则就是各种hack

**Comment by lifesinger** [comment]
@lianqin7 上面的这个问题，@popomore 再仔细考虑下，值得商榷。

关于 beforeXxx 的讨论，或 @lianqin7 上面的提议，昨天在 14F 跟 lianqin7 当面也有聊到，核心考虑是

**让实例的初始化可以通过 JSON 自描述。**

典型范例是，ExtJS 的做法，这样使用者不用关系实例，只要关心实例的配置，这种配置是可以持久化 + 传递的。

考虑 Arale 以后要支持前端服务化，保持可配置的完备性，感觉还是有必要的。

**Comment by lianqin7** [comment]
@popomore 

其实我在前面说了那么多废话，目的只有一个：

希望 **能够在初始化的时候给实例绑定事件**

所以无论是 `onXxx` 的方式，还是 `on: {}` ，或者是 **其他什么api**，目的都是一致的

这样做的好处主要有2点：
1. 像 @lifesinger 所说的， **用JSON自描述实例化**
2. 解决一些类似于 **initialize/setup中触发的事件绑定** 的问题

**Comment by popomore** [comment]
Arale 本身是一套类库。

不管是 data-api，前端服务化或是 extjs 的做法更像是一种模式，应该在 Arale 上层去做封装。

比如之前说的工厂模式，就可以将 json 转化成 Arale 的组件调用方式。而 data-api 可以把 DOM 的属性转化成 Arale 的组件调用方式，之前也考虑过把 autoRender 从 widget 中独立出来。

initialize 我觉得组件开发者没做好，在实例化的时候还需要特殊处理，真需求完全可以继承自己开发。

**Comment by popomore** [comment]
根据今天的讨论先不去掉了，本版本先回滚代码，有什么新方案在下个版本增加。

**Comment by nuintun** [comment]
囧，算了，我还是不回滚了吧，保持单一性！
