### ISSUE TITLE
Attribute性能问题

### ISSUE THREAD

**Issue by lianqin7** [aralejs/base#17]
![image](https://f.cloud.github.com/assets/2155909/435480/86cdf090-afdc-11e2-9490-5f028ab5caa1.png)

如图所示，在一个有 **144个模块的中等复杂度的表单页面** ，除开seajs的一些函数调用，最废时间的就是 attitude 里的 `isPlainObject` 和 `merge` 方法，这块是否能有提升的空间？

**Comment by lifesinger** [comment]
应该可以优化，五一后好好看下

On Sun, Apr 28, 2013 at 4:22 PM, lianqin7 notifications@github.com wrote:

> [image: image]https://f.cloud.github.com/assets/2155909/435480/86cdf090-afdc-11e2-9490-5f028ab5caa1.png
> 
> 如图所示，在一个有 _144个模块的中等复杂度的表单页面_ ，除开seajs的一些函数调用，最废时间的就是 attitude 里的
> isPlainObject 和 merge 方法，这块是否能有提升的空间？
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aralejs/base/issues/17
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by lianqin7** [comment]
@popomore @lifesinger 

稍微的提醒一下：）

**Comment by popomore** [comment]
@lianqin7 这个性能问题可能跟 #19 也有关系，你们有没有用某个除了 Element 的复杂对象作为属性的场景。像例子里面的 moment。

**Comment by popomore** [comment]
目前优化的进度 http://jsperf.com/arale-attribute/2

**Comment by lianqin7** [comment]
赞！

**Comment by popomore** [comment]
目前 merge 和 isPlainObject 的执行次数减少了一半左右，但仍然还是 attribute 最耗时间的。

如再提高性能，需要整体重构了，影响比较大，视运行情况而定。
