### ISSUE TITLE
attribute做了非兼容修改照成validator中onItemValidate等事件失效

### ISSUE THREAD

**Issue by nuintun** [aralejs/base#18]
如题，由于`attribute`去掉了以下代码：

``` js
var EVENT_PATTERN = /^(on|before|after)([A-Z].*)$/;
var EVENT_NAME_PATTERN = /^(Change)?([A-Z])(.*)/;
//......
```

照成validator中onItemValidate等时间失效，现在只能用下面方式绑定：

``` js
validator.on('itemValidate', handler);
```

是否以后就只用第二种方式绑定了？

**Comment by popomore** [comment]
对，base 还未发布，validator 升级的时候会做相应修改 #15

**Comment by lianqin7** [comment]
https://github.com/aralejs/base/issues/15#issuecomment-17581210

个人觉得这种修改是有待商榷的

**Comment by nuintun** [comment]
各有优缺点吧，大部分人可能更倾向于`attrs`的写法，不过事件方式更符合`DOM`事件的监听机制，比较统一！
