### ISSUE TITLE
attr copy bug in ie

### ISSUE THREAD

**Issue by lepture** [aralejs/base#19]
https://github.com/aralejs/base/blob/master/tests/base-spec.js#L793

在 IE 下是 false.

**Comment by popomore** [comment]
isPlainObject 的判断问题，这段是复制 jquery，见 bugfix

http://bugs.jquery.com/ticket/12199

对象遍历的时候 ie6~8 是先遍历原型链上再遍历自己，其他浏览器相反

也可以参考下 lodash 的

https://github.com/bestiejs/lodash/blob/7520066fc916e205ef84cb97fbfe630d7c154158/lodash.js#L720-757
