### ISSUE TITLE
attribute代码严重bug

### ISSUE THREAD

**Issue by lianqin7** [aralejs/base#22]
简单还原代码如下：

``` js
seajs.use('widget', function(Widget){
    var t = new Widget();
    t.set('parentNode', document.getElementById('show'));
    t.render();
});
```

IE8及以下报 **对象不支持“hasOwnProperty”属性或方法**

原因在这：https://github.com/aralejs/base/blob/master/src/attribute.js#L97

`isEqual`方法内部会最终调用到`isEmptyObject`，但是没有做`isPlainObject`的保护判断，所以报错（ **IE8及以下的原生dom没有hasOwnProperty** ）

**Comment by lizzie** [comment]
貌似是在实例化 widget 之后才 set parentNode 的问题, 把 parentNode 作为参数传入 Widget, 不会出现 "hasOwnProperty" 的报错.

**Comment by lizzie** [comment]
set("parentNode", xx) 时, 比较的是 当前 parentNode 的值即 document.body 和 xx 是否相等.  document.body.hasOwnProperty 却为 undefined ..

**Comment by lizzie** [comment]
最终原因是: 

isEmptyObject() 中 Object.prototype.toString.call(document.body) 在 <=IE8 下也为 "[object Object]" , 所以添加判断条件 o.nodeType || isWindow(o)

**Comment by popomore** [comment]
之前一直没注意，这段逻辑在实例化的时候不会触发，只有调用 set 的时候才触发，所以使用 parentNode 的时候一直没问题。
