### ISSUE TITLE
初始化性能优化思路及简单结果

### ISSUE THREAD

**Issue by lianqin7** [aralejs/base#24]
目前 `mergeInheritedAttrs` 及 `mergeUserValue` 是 base 初始化过程中性能消耗最大的部分。针对这2段逻辑，想了一些优化方案。
- 优化这2个方法内部的 merge 方法
  
  因为操作的都是标准的格式化后的 attr 属性，不需要做 `isPlainObject` 判断，这个可以省掉不少，然后因为只有 value 的类型是不定的，所以只要针对 value 做merge即可，其他（getter等）可以直接用新值覆盖就值，又可以省一笔开销。
  
  这部分 **优化效果 5% - 10% 左右**
- 更深入的思考： **为什么每次在实例初始化的时候才去计算整条原型继承链的 attrs ？** 
  
  这个思路本身就是有问题的，浪费了多少无效的时间（在一个类被多次实例化的时候特别明显）。所以，将 **格式化及合并继承 attrs 的工作** 在 extend 的时候完成，就可以减少掉这种浪费！
  
  **优化效果** ：只是简单的改了下方式，细节还没调整，结果可以看这里：http://jsperf.com/arale-base-performance  **效果很明显！！**

缺点 & 改进点： 这种修复方法 hack 了 `Class.create`，是因为没有别的方法在 extend 的时候做些额外的事情，这个考虑优化下 class 模块？提供下相应的处理方式。

@lifesinger @afc163 @popomore

**Comment by lianqin7** [comment]
http://jsperf.com/arale-base-performance 

效果明显的原因是： **一个原型被N多次的初始化了** ，如果是那种 **一个原型只会被初始化一次的场景，效果提升就不明显了，可能还会有些反作用**

不过 **优化这2个方法内部的 merge 方法** 的提升是无视场景的，这个修改我会先 pull 过来的

**Comment by lianqin7** [comment]
先close掉，每个问题独立讨论解决

**Comment by lifesinger** [comment]
嗯，单开 issue，独立讨论

On Mon, Jul 8, 2013 at 2:53 PM, lianqin7 notifications@github.com wrote:

> 先close掉，每个问题独立讨论解决
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aralejs/base/issues/24#issuecomment-20588440
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香
