### ISSUE TITLE
attribute 添加 modify 接口

### ISSUE THREAD

**Issue by popomore** [aralejs/base#29]
经常会只修改某个属性，比如 count，总是要先 get 计算后再 set

```
var count = this.get('count');
this.set('count', count++);
```

尤其处理对象的时候比较麻烦，写多了有点恶心

```
var model = this.get('model');
model.content = model.head + model.body + model.foot;
this.set('model', model);
```

提供 modify 方法

```
this.modify('count', function(count) {
  return count++;
});

this.modify('model', function(model) {
  return {
    content: model.head + model.body + model.foot
  };
});
```

**Comment by lifesinger** [comment]
不是很认可添加这个语法糖。原来的代码看起来多些，但挺清晰的。

基础模块，我觉得我们可以遵循 Go 语言的最小心智负担原则，包括
1. 最小特性
2. 最小惊异
3. 最小犯错机会

最小特性原则指的是：如果一个功能不对解决任何问题有显著价值，那么就不提供。

如果我们能达成一致认可上面的原则的话，那么 modify 就没必要提供。还有一个原因是，modify 是个很好很常见的方法名，很容易被实例上的方法覆盖掉。YUI 有提供 modifyAttr 方法，但功能不一样。Backbone 则没有提供，保持功能的精简。

**Comment by popomore** [comment]
好，要使用可以自己添加
—
