### ISSUE TITLE
Attribute.js 两处问题

### ISSUE THREAD

**Issue by arcthur** [aralejs/base#8]
Attribute.js Line 208

``` javascript
value = value.slice();
```

应为

``` javascript
value = slice.call(value)
```

另，jQuery的isPlainObject实现在IE8是有bug的，使用一个NodeList实际上它不会走到catch里

**Comment by popomore** [comment]
没看明白，能否 fork 一份写个测试用例？

**Comment by lifesinger** [comment]
208 行应该没问题，因为前置条件是，value 是 array，有 slice 方法。

isPlainObject 可以给一个具体的例子，我刚才在 ie8 下试了下 nodelist 是返回 false，没问题的。

**Comment by popomore** [comment]
先关了，如有问题再 reopen
